# Generated by Django 4.1.6 on 2023-03-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sub_category_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnails/'),
        ),
    ]
