# Generated by Django 4.1.6 on 2023-03-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_blog_thumbnail_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
