# Generated by Django 4.1.6 on 2023-03-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='Thumbnail',
        ),
    ]
